# Tasks to pause the machine reboots triggered by machine config changes.
# Ref:
#   https://docs.openshift.com/container-platform/4.5/rest_api/machine_apis/machineconfigpool-machineconfiguration-openshift-io-v1.html

- name: Get list of current MCPs
  k8s_info:
    api_version: machineconfiguration.openshift.io/v1
    kind: MachineConfigPool
  register: reg_mcp

- name: Patch MCP spec to reflect paused = true
  k8s:
    state: present
    definition:
      apiVersion: machineconfiguration.openshift.io/v1
      kind: MachineConfigPool
      metadata:
        name: "{{ mcp_name }}"
      spec:
        paused: true
  loop: "{{ reg_mcp.resources }}"
  loop_control:
    label: "{{ mcp_name }}"
  vars:
    mcp_name: "{{ item.metadata.name }}"
