- name: Get current clusters etcd member pods
  k8s_facts:
    api_version: v1
    kind: Pod
    namespace: openshift-etcd
  register: reg_etcd_pods

- name: Set etcd_image fact
  set_fact:
    etcd_image: "{{ container_image }}"
  vars:
    etcd_pod: "{{reg_etcd_pods.resources[0] }}"
    image_query: "spec.containers[?name=='etcd-member'].image"
    container_image: "{{ (etcd_pod | json_query(image_query))[0] }}"
