
- name: Get current cluster's etcd image
  command: oc adm release info --image-for etcd
  register: reg_etcd_image

- name: Set etcd_image fact
  set_fact:
    etcd_image: "{{ reg_etcd_image.stdout }}"

