---

- name: Create ServiceAccount
  k8s:
    state: present
    namespace: "{{ splunk_connect_namespace }}"
    definition: "{{ lookup('template', 'splunk-kubernetes-logging/serviceAccount.yaml.j2') }}"
  register: reg_splunk_kubernetes_logging_sa

- name: Create ConfigMap
  k8s:
    state: present
    namespace: "{{ splunk_connect_namespace }}"
    definition: "{{ lookup('template', 'splunk-kubernetes-logging/configMap.yaml.j2') }}"

- name: Create Secret
  k8s:
    state: present
    namespace: "{{ splunk_connect_namespace }}"
    definition: "{{ lookup('template', 'splunk-kubernetes-logging/secret.yaml.j2') }}"

- name: Add scc to user
  shell: "oc adm policy add-scc-to-user privileged system:serviceaccount:{{ splunk_connect_namespace }}:splunk-kubernetes-logging"
  when:
    - reg_splunk_kubernetes_logging_sa.changed

- name: Create Daemonset
  k8s:
    state: present
    namespace: "{{ splunk_connect_namespace }}"
    definition: "{{ lookup('template', 'splunk-kubernetes-logging/daemonset.yaml.j2') }}"
