---
splunk_connect_namespace: "splunk-connect"

splunk_connect_version: 1.4.1
splunk_connect_fluentd_image: "docker.io/splunk/fluentd-hec:1.2.2"
splunk_connect_k8s_objects_image: "docker.io/splunk/kube-objects:1.1.3"

# Splunk endpoint configuration parameters.
splunk_hec_host: splunk.example.com
splunk_hec_ca_cert_file: "splunk-hec-ca.crt"

# each index can have separate hec tokens
splunk_logging_hec_token: 5d4a219a-46dd-4da8-b6e4-3b810d685c72
splunk_objects_hec_token: eb0771d7-7f78-4ef3-9825-acd94120b51b

splunk_cluster_id: 'opentlc'

# Assuming we are going to be using separate index for each of the 3 components
# - container logs
# - OpenShift objects
# - Openshift metrics

# Name of the index in splunk to send logs to.
splunk_k8s_logging_index: container-logs
splunk_k8s_objects_index: k8s-objects
# splunk_k8s_metrics_index: k8s-metrics
# Possible index to send metrics data to
